name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t myapp:latest -f ./my-app/Dockerfile ./my-app

      - name: Save Docker image to tar file
        run: docker save myapp:latest -o image.tar

      - name: Copy Docker image to Droplet
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          target: /home/${{ secrets.DROPLET_USERNAME }}/image.tar
          source: image.tar

      - name: Load Docker image on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.DROPLET_SSH_KEY }} ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }} 'docker load -i /home/${{ secrets.DROPLET_USERNAME }}/image.tar'
