name: Build, Push, and Deploy to DigitalOcean Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to DigitalOcean Docker registry
      run: echo "${{ secrets.DIGITALOCEAN_PASSWORD }}" | docker login -u "${{ secrets.DIGITALOCEAN_USERNAME }}" --password-stdin registry.digitalocean.com

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./my-app
        file: ./my-app/Dockerfile
        push: true
        tags: registry.digitalocean.com/testekubernerts/my-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
        kubectl config view
        kubectl config use-context digitalocean

    - name: Update Kubernetes deployment
      run: |
        kubectl set image deployment/my-app-deployment your-container=registry.digitalocean.com/testekubernerts/my-app:latest
        kubectl rollout status deployment/my-app-deployment
