name: Construir e Implantar Imagem Docker

on:
  push:
    branches:
      - main

jobs:
  construir-e-implantar:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Verificação do Repositório
      - name: Verificar repositório
        uses: actions/checkout@v2

      # Etapa 2: Construção da Imagem Docker
      - name: Construir imagem Docker
        run: docker build -t myapp:latest -f ./my-app/Dockerfile ./my-app

      # Etapa 3: Salvando a Imagem Docker em um Arquivo TAR
      - name: Salvar imagem Docker em arquivo TAR
        run: docker save myapp:latest -o image.tar

      # Etapa 4: Copiando a Imagem Docker para o Droplet
      - name: Copiar imagem Docker para o Droplet
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          target: /home/${{ secrets.DROPLET_USERNAME }}/image.tar
          source: image.tar

      # Etapa 5: Carregar a Imagem Docker do Arquivo TAR
      - name: Carregar imagem Docker a partir do arquivo TAR
        run: docker load -i image.tar

      # Etapa 6: Verificar se a Imagem Docker foi carregada corretamente
      - name: Verificar se a imagem Docker está carregada
        run: docker images | grep myapp
