name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Verificação do Repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Etapa 2: Construção da Imagem Docker
      - name: Build Docker image
        run: docker build -t myapp:latest -f ./my-app/Dockerfile ./my-app

      # Etapa 3: Salvando a Imagem Docker em um Arquivo TAR
      - name: Save Docker image to tar file
        run: docker save myapp:latest -o image.tar

      # Etapa 4: Copiando a Imagem Docker para o Droplet
      - name: Copy Docker image to Droplet
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          target: /home/${{ secrets.DROPLET_USERNAME }}/image.tar
          source: image.tar
